[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "commandchat"
version = "0.0.15"
description = "Command-line chat client for OpenAI and Azure OpenAI models."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "tao", email = "xxx.tao.c@gmail.com" }
]
dependencies = [
    "click",
    "openai",
    "Pillow",
    "prompt_toolkit",
    "Pygments",
    "pyperclip",
    "questionary",
    "requests",
    "rich",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/xoto/commandchat"
Issues = "https://github.com/xoto/commandchat/issues"

[project.scripts]
occ = "occ.command.__main__:main"

[tool.setuptools.packages.find]
include = ["occ*"]

